---
title: 'Task 1: Agglomerative Hierarchical Clustering'
author: "Laurel Wee"
date: "3/6/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(naniar)
library(NbClust)
```

```{r}
# Read in steam chemistry data from https://drive.google.com/file/d/16rYLBi-CgvjcWhOsX1SLdD9HHUMP9m2l/view?usp=sharing
stream_chem <- read.csv(here("data","sbc_lter_registered_stream_chemistry - sbc_lter_registered_stream_chemistry.csv")) %>% 
  na_if(-999.0)%>% # turn `-999.0` values into NA
  select(site_code, ends_with("uM"))
         #nh4_uM,no3_uM,po4_uM) # Select `site_code` mirco-molar concentration columns
```

```{r}
# Make a new dataframe that includes the average of each measurement by site
stream_avg <-stream_chem %>% 
  group_by(site_code) %>% 
  summarise_all(mean, na.rm=TRUE)

# Make `site_code` the rownames of the averaged data frame
rownames(stream_avg)<-stream_avg$site_code

# Scale the averaged dataframe
stream_scale <- stream_avg %>% 
  select(ends_with("uM")) %>% 
  na.omit() %>% 
  scale()
```

```{r}
# Compute dissimilarity values (Euclidean distances):
euc_distance <- dist(stream_scale, method = "euclidean")

#View(euc_distance)

# Hierarchical clustering (complete linkage)
hc_complete <- hclust(euc_distance, method = "complete" ) 

# Make a dendrogram visual
ggdendrogram(hc_complete,
             rotate = TRUE)+
  theme_minimal()+
  labs(x="Creek Site", y="Height")
  
```
####  Data Citation:
Santa Barbara Coastal LTER and J. Melack. 2019. SBC LTER: Land: Stream chemistry in the Santa Barbara Coastal drainage area, ongoing since 2000 ver 16. Environmental Data Initiative. https://doi.org/10.6073/pasta/67a558a24ceed9a0a5bf5e46ab841174. 

